name: "Feature request"
description: Create a feature request for Denji
title: '[feat]: '
labels: ['area: request']
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a feature request! Please search open/closed issues before submitting, as the issue may have already been reported/addressed.
 
  - type: markdown
    attributes:
      value: |
        #### If you aren't sure this is a bug or not, please open a discussion instead:
        - [Discussions](https://github.com/fellipeutaka/denji/discussions/new?category=general)

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request
      placeholder: 'I think this feature would be great because...'
      value: 'Describe your feature request...'
    validations:
      required: true

  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected area(s)
      description: Which parts of Denji would be impacted by this feature?
      options:
        - label: CLI
        - label: Generators
        - label: Framework adapters
        - label: Icon registry integration
        - label: Documentation
        - label: Other / Not sure
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature here.
      placeholder: "Links, screenshots, references, examples, etc."
      value: "Additional details here..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/fellipeutaka/denji/blob/main/CONTRIBUTING.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues and PRs
          required: true